CivixElectricianItems = {
    electrician_toolkit = { name = 'electrician_toolkit', label = 'Electrician Toolkit', weight = 2800, type = 'item', image = 'electrician_toolkit.svg', unique = true, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = false, description = 'A professional insulated field toolkit issued for electrical service work.' },
    digital_multimeter = { name = 'digital_multimeter', label = 'Digital Multimeter', weight = 650, type = 'item', image = 'digital_multimeter.svg', unique = true, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = false, description = 'A calibrated meter used to test voltage, continuity and resistance.' },
    insulated_gloves = { name = 'insulated_gloves', label = 'Insulated Work Gloves', weight = 420, type = 'item', image = 'insulated_gloves.svg', unique = true, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = false, description = 'Class-rated rubber gloves for live electrical service environments.' },
    lockout_tag = { name = 'lockout_tag', label = 'Lockout Tag', weight = 80, type = 'item', image = 'lockout_tag.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A serialized safety tag used to isolate an electrical circuit before repair.' },
    electrical_connector = { name = 'electrical_connector', label = 'Electrical Connector', weight = 120, type = 'item', image = 'electrical_connector.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A high-current insulated connector for replacing burnt service terminals.' },
    copper_wire = { name = 'copper_wire', label = 'Copper Wire', weight = 260, type = 'item', image = 'copper_wire.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A measured length of insulated copper conductor for field repairs.' },
    service_fuse = { name = 'service_fuse', label = 'Service Fuse', weight = 180, type = 'item', image = 'service_fuse.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A properly rated cartridge fuse used in municipal service cabinets.' },
    control_relay = { name = 'control_relay', label = 'Control Relay', weight = 240, type = 'item', image = 'control_relay.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A sealed low-voltage relay for municipal lighting and utility controllers.' },
    terminal_block = { name = 'terminal_block', label = 'Terminal Block', weight = 210, type = 'item', image = 'terminal_block.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A replacement terminal assembly for corroded electrical cabinet connections.' },
    grounding_clamp = { name = 'grounding_clamp', label = 'Grounding Clamp', weight = 340, type = 'item', image = 'grounding_clamp.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A heavy copper grounding clamp used to restore safe fault-current paths.' },
    electrical_tape = { name = 'electrical_tape', label = 'Electrical Tape', weight = 100, type = 'item', image = 'electrical_tape.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'Professional-grade insulating tape for protected conductor repairs.' },
}
