CivixGridServiceItems = {
    grid_toolkit = { name = 'grid_toolkit', label = 'Grid Service Toolkit', weight = 2800, type = 'item', image = 'grid_toolkit.svg', unique = true, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = false, description = 'A professional insulated field toolkit issued for municipal grid service work.' },
    grid_multimeter = { name = 'grid_multimeter', label = 'Grid Multimeter', weight = 650, type = 'item', image = 'grid_multimeter.svg', unique = true, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = false, description = 'A calibrated digital meter used to test voltage, continuity and resistance.' },
    grid_gloves = { name = 'grid_gloves', label = 'Insulated Grid Gloves', weight = 420, type = 'item', image = 'grid_gloves.svg', unique = true, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = false, description = 'Class-rated insulated gloves used during municipal electrical cabinet repairs.' },
    grid_lockout_tag = { name = 'grid_lockout_tag', label = 'Grid Lockout Tag', weight = 80, type = 'item', image = 'grid_lockout_tag.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A serialized safety tag used to isolate a cabinet circuit before field service.' },
    grid_connector = { name = 'grid_connector', label = 'Grid Terminal Connector', weight = 120, type = 'item', image = 'grid_connector.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A high-current insulated connector for replacing burnt municipal service terminals.' },
    grid_wire = { name = 'grid_wire', label = 'Grid Copper Wire', weight = 260, type = 'item', image = 'grid_wire.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A measured length of insulated copper conductor used for cabinet wiring repairs.' },
    grid_service_fuse = { name = 'grid_service_fuse', label = 'Grid Service Fuse', weight = 180, type = 'item', image = 'grid_service_fuse.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A properly rated cartridge fuse used in municipal distribution cabinets.' },
    grid_control_relay = { name = 'grid_control_relay', label = 'Grid Control Relay', weight = 240, type = 'item', image = 'grid_control_relay.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A sealed low-voltage relay used by lighting and utility control cabinets.' },
    grid_terminal_block = { name = 'grid_terminal_block', label = 'Grid Terminal Block', weight = 210, type = 'item', image = 'grid_terminal_block.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A replacement terminal assembly for corroded electrical cabinet connections.' },
    grid_grounding_clamp = { name = 'grid_grounding_clamp', label = 'Grid Grounding Clamp', weight = 340, type = 'item', image = 'grid_grounding_clamp.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'A heavy copper clamp used to restore a safe fault-current path.' },
    grid_electrical_tape = { name = 'grid_electrical_tape', label = 'Grid Electrical Tape', weight = 100, type = 'item', image = 'grid_electrical_tape.svg', unique = false, useable = false, shouldClose = true, combinable = nil, degrade = 100, decay = false, delete = true, description = 'Professional-grade insulating tape used to protect completed conductor repairs.' }
}
