CREATE TABLE IF NOT EXISTS `civix_gridservice_progress` (
    `citizenid` VARCHAR(64) NOT NULL,
    `xp` INT UNSIGNED NOT NULL DEFAULT 0,
    `completed_repairs` INT UNSIGNED NOT NULL DEFAULT 0,
    `failed_repairs` INT UNSIGNED NOT NULL DEFAULT 0,
    `total_earnings` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
